### ISSUE TITLE
Correct installation, but it does not start

### ISSUE THREAD

**Issue by jmroldan1975** [tubiana/TTClust#12]
Hi,

I have correctly installed TTClust under Mac OSX, but when I try to use the program I get the following error message: 
```
Traceback (most recent call last):
  File "/Users/admin/anaconda2/bin/ttclust", line 7, in <module>
    from ttclust.ttclust import main
  File "/Users/admin/anaconda2/lib/python2.7/site-packages/ttclust/ttclust.py", line 22, in <module>
    sys.executable = shutil.which("pythonw")
AttributeError: 'module' object has no attribute 'which'
```

Can you help me? Thanks.

**Comment by tubiana** [comment]
Sorry for taking so long to answer...
I don't own a Mac so it is not always easy to fix issues on it. But now it should work! `which `was added in `shutil` after Python 3.3 so it was not compatible with Python 2. 
I add a custom `which` function to fix this.
I close this issues, don't hesitate to re-open if it's still bugged.

Kind regards,
Thibault.
