### ISSUE TITLE
Clustering multiple trajectories

### ISSUE THREAD

**Issue by shozebhaider** [tubiana/TTClust#14]
Hi, I have several trajectories on which I want to perform clustering on. Does TTclust do clustering on multiple trajectories? It is not possible to concatenate them into one and hence the question.   
Many thanks.

**Comment by tubiana** [comment]
Thank you for your idea, functionality added :-) 

Several trajectories can be loaded with:
`ttclust -t topol.pdb -f traj1.xtc traj2.xtc traj3.xtc `. 
or 
`ttclust -t topol.pdb -f *.xtc`

I close the issue, you can open it again if you have bugs!

Best,
thibault.
