### ISSUE TITLE
File name size

### ISSUE THREAD

**Issue by rupeshagarwal** [tubiana/TTClust#23]
OSError: [Errno 36] File name too long: '(residue_340_341_342_343_344_345_346_347_348_372_435_439_440_441_442_443_444_445_446_448_449_450_452_481_516_517_519_520_521_523_524_525_526_527_528_529_530_531_532_594_596_597_598_599_602_603_605_606_609_610_611_612_613_615_616_617_618_619_620_621_622_623)_and_backbone.npy'

**Comment by tubiana** [comment]
Hi,

1. Could you be more specific please ? Is that during the reading (second execution) or writing (first execution) ? 
2. Then could you put the full error output please.

I Can think of a quick fix, but please I need those information first.
Best regards,
Thibault.

**Comment by rupeshagarwal** [comment]
Hi Tubiana,

Great tool! A small issue: I wanted to cluster my trajectory based on ~60 residues and since the numpy file is named <resid_used_to_cluster>.npy, I was getting an error because I chose 60 residues and the file name was too long. I changed the resid selection to a range and it worked fine. I hope this makes sense.

**Comment by tubiana** [comment]
Yes, it makes sense :) 
To "save" computational time, I save the distance matrix based on the selection name (so if you want to run the clustering with different parameters on the same selection based, you don't need to compute the distance matrix again), but I didn't think of the length of the filename...

I will patch it shortly (in the next day), I will convert the selection string in a MD5 hashed filename instead which will be shorter :)

**Comment by tubiana** [comment]
hi!

Sorry that it took so much time for me to take the time to fix this.
It should work now with your first selection string.
When the filename is too long, it is now hashed with the MD5 algorithm.

So please update TTClust to version 4.9.0 through conda or pypi.

I close the issue, just open it if something goes wrong again :) 

Best regards,
Thibault.
