### ISSUE TITLE
problem in clustering MDS when the protein moves out from one edge of water box while applying periodic boundary conditions

### ISSUE THREAD

**Issue by hima111997** [tubiana/TTClust#24]
Hi!
I have clustered an MDS trajectory in which the protein moves out from the water box from one side and enters from the other side. TTClust is not able to cluster it well because the representative frames are like this image

![image](https://user-images.githubusercontent.com/55895327/111883858-80101680-89c6-11eb-8f2b-cec0ac39b6e6.png)

Is there a solution to this problem?

Thanks

**Comment by tubiana** [comment]
Hi!

TTClust only perform the clustering, all the "cleaning" has to be done prior to TTClust execution. 
For example, I usually clean my trajectories by removing the waters, making the molecule whole again and aligning the protein on itself through the trajectory.
If you used Gromacs it is the "trjconv" tools. 
If you want more details, you can check my Gromacs tutorial (part 4.2) http://tubiana.me/teaching_files/biocat2020/Tutorial_Gromacs-2019.pdf 
Best regards,
Thibault.

**Comment by hima111997** [comment]
Thanks I use vmd to fix the structure then clustered and it worked

Sent from Yahoo Mail on Android 
 
  On الأحد, مارس ٢١, ٢٠٢١ at ٢:٠٢ م, Thibault ***@***.***> wrote:   


Hi!

TTClust only perform the clustering, all the "cleaning" has to be done prior to TTClust execution.
For example, I usually clean my trajectories by removing the waters, making the molecule whole again and aligning the protein on itself through the trajectory.
If you used Gromacs it is the "trjconv" tools.
If you want more details, you can check my Gromacs tutorial (part 4.2) http://tubiana.me/teaching_files/biocat2020/Tutorial_Gromacs-2019.pdf
Best regards,
Thibault.
