### ISSUE TITLE
Clustering with only .pdb file (without .xtc file)

### ISSUE THREAD

**Issue by JeanMi2021** [tubiana/TTClust#26]
My simulation is done by openMM and hasn't generated the .xtc file. Only trajectory.pdb file is included. In this case, can I use this package for clustering? Thanks for your answer in advance.

**Comment by tubiana** [comment]
Hi!

I'm so sorry for this long delay, I think I completely miss the email notification.
It should work but I haven't tested it lately. Just open the ticket again if you have any issues and I will fix it.

Best,
Thibault.
