### ISSUE TITLE
what is the unit of RMSD in the log file ?

### ISSUE THREAD

**Issue by hima111997** [tubiana/TTClust#28]
in the log file produced from clustering, there are cutoff for clustering, RMSD between clusters, and average RMSD. Can you tell me what are the units for each one?

**Comment by tubiana** [comment]
Hi !

The unit for the RMSD is in angstrom. But there is no unit (or Arbitrary Unit) for the cutoff value since it is a hierarchical distance. It corresponds to the value in the dendrogram on the Y-axis.
