### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\CLOUDS\\GoogleDrive\\WORK\\Perso\\DEV\\ttclust\\examples'

### ISSUE THREAD

**Issue by Tangbbmc** [tubiana/TTClust#35]
I have successfully installed ttclust on my Ubuntu system by conda with the command (conda install -c tubiana -c conda-forge ttclust). Now, I would like to install the GUI version of ttclust. For this purpose, the ttclustGUI.py  has been placed in the same directory of ttclust.py (miniconda3/envs/ttclust/lib/python3.10/site-packages/ttclust). When running the command python ttclustGUI.py, the terminal reported the following error, could you tell me how to deal with it?

(ttclust) twg@TWG:~/miniconda3/envs/ttclust/lib/python3.10/site-packages/ttclust$ python ttclustGUI.py
Traceback (most recent call last):
  File "/home/twg/miniconda3/envs/ttclust/lib/python3.10/site-packages/ttclust/ttclustGUI.py", line 170, in <module>
    main()
  File "/home/twg/miniconda3/envs/ttclust/lib/python3.10/site-packages/ttclust/ttclustGUI.py", line 122, in main
(ttclust) twg@TWG:~/miniconda3/envs/ttclust/lib/python3.10/site-packages/ttclust$ python ttclustGUI.py
Traceback (most recent call last):
  File "/home/twg/miniconda3/envs/ttclust/lib/python3.10/site-packages/ttclust/ttclustGUI.py", line 170, in <module>
    main()
  File "/home/twg/miniconda3/envs/ttclust/lib/python3.10/site-packages/ttclust/ttclustGUI.py", line 122, in main
    os.chdir("D:\\CLOUDS\\GoogleDrive\\WORK\\Perso\\DEV\\ttclust\\examples")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\CLOUDS\\GoogleDrive\\WORK\\Perso\\DEV\\ttclust\\examples'

**Comment by tubiana** [comment]
Hi.
The GUI is deprecated sorry, Plus It had some compatibility issues with recent libraries.  I do not have time to maintain it by myself at the moment...

You will have to use the command line version sorry about that!

Best
Thibault.

**Comment by Tangbbmc** [comment]
Ok. I see. Thanks for your reply! I expect the release of your new GUI version.

发件人：Thibault Tubiana ***@***.***>
发送日期：2023-02-24 02:43:22
收件人：tubiana/TTClust ***@***.***>
抄送人：Tangbbmc ***@***.***>,Author ***@***.***>
主题：Re: [tubiana/TTClust] FileNotFoundError: [Errno 2] No such file or directory: 'D:\\CLOUDS\\GoogleDrive\\WORK\\Perso\\DEV\\ttclust\\examples' (Issue #35)

Hi.
 The GUI is deprecated sorry, Plus It had some compatibility issues with recent libraries. I do not have time to maintain it by myself at the moment...
You will have to use the command line version sorry about that!
Best
 Thibault.
