### ISSUE TITLE
Clustering of host guest systems

### ISSUE THREAD

**Issue by sameersaurav** [tubiana/TTClust#39]
Hi there,

I want to align my trajectory along atoms from, serial 1 to 148.
I tried following commands -
ttclust -f 200ns.xtc -t Umb_1.pdb -sa "index 1 to 148"
tclust -f 200ns.xtc -t Umb_1.pdb -sa "index <= 147"

Error-

NOTE : Extraction of subtrajectory for time optimisation
ERROR : there is an error with your selection string
        SELECTION STRING : 
        backbone

Kindly suggest the correct syntax for sa.
 Thank you for your help.

**Comment by tubiana** [comment]
Hi! 

`-sa` is for the alignement of the trajectory. To give a selection for the clustering, the right argument is `-sr`. If you wanna align and cluster on the selection you gave I suggest to try this command :
``` 
ttclust -f 200ns.xtc -t Umb_1.pdb -sa "index 1 to 148" -sr "index 1 to 148"
tclust -f 200ns.xtc -t Umb_1.pdb -sa "index <= 147 -sr "index 1 to 148"
```

Kind regards
Thibault

**Comment by sameersaurav** [comment]
Dear Thibault,

Thanks a lot.

With regards
Sameer
